version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - /dockerfiles/server
      - /dockerfiles/dashboard
    schedule:
      interval: weekly
    groups:
      docker:
        patterns:
          - "*"
